### ISSUE TITLE
TravHarv subjects must be made when task is started , not when config builder is called

### ISSUE THREAD

**Issue by cedricdcc** [vliz-be-opsci/pyTravHarv#48]
With the following config:
```yaml
snooze-till-graph-age-minutes: 0
prefix:
  rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
  dcat: <http://www.w3.org/ns/dcat#>
  schema: <https://schema.org/>
  org: <http://www.w3.org/ns/org#>
  dct: <http://purl.org/dc/terms/>
  mi: <http://www.marineinfo.org/ns/ontology#>
assert:
  - subjects:
      literal:
        - http://dev.marineinfo.org/id/collection/947 # WoRMS ackn - direct
    paths:
      - "<http://www.w3.org/ns/dcat#resource> "
  - subjects:
      SPARQL: >
        SELECT DISTINCT ?s
        WHERE {
              [] <http://www.w3.org/ns/dcat#resource> ?s .
              }
    paths:
      - "<https://schema.org/author>"
  - subjects:
      SPARQL: >
        PREFIX schema: <https://schema.org/>
        SELECT DISTINCT ?s
        WHERE {
          ?ok <https://schema.org/author> ?authorid .
          ?authorid <https://schema.org/identifier> ?s .
        }
    paths:
      - "<https://schema.org/affiliation>"
      - "<https://schema.org/givenName>"
      - "<https://schema.org/familyName>"
  - subjects:
      SPARQL: >
        SELECT DISTINCT ?affid
        WHERE {
            ?s <https://schema.org/affiliation> ?affid .
        }
    paths:
      - "<https://schema.org/name>"
 ```
 Travharv does not dereference the publications from a given dataset.
 However on the next run it does.
 
 The same issue has been detected for the LWUA where @laurianvm had to rerun the sembench container for the publications to be dereferenced.
